export const S = {
  input: {
    width: "100%",
    background: "#111",
    border: "1px solid #333",
    borderRadius: 8,
    padding: "10px 13px",
    color: "#e8e8e8",
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12,
    outline: "none",
  },
  btnSm: {
    background: "#181818",
    border: "1px solid #333",
    borderRadius: 5,
    padding: "3px 10px",
    color: "#aaa",
    fontFamily: "monospace",
    fontSize: 9,
    cursor: "pointer",
  },
  btnPrimary: {
    background: "#FF0000",
    color: "#fff",
    border: "none",
    borderRadius: 7,
    padding: "9px 18px",
    fontFamily: "'Syne', sans-serif",
    fontWeight: 700,
    fontSize: 12,
    cursor: "pointer",
  },
  label: {
    fontFamily: "monospace",
    fontSize: 9,
    color: "#666",
    textTransform: "uppercase",
    letterSpacing: "1px",
    display: "block",
    marginBottom: 4,
  },
};
